import { writable } from "svelte/store";

export const importDocumentSrc = writable('@plantir/uikit')
export const themes = writable([
    "light",
    "luxury",
    "aqua",
    "synthwave",
    "polaris",
    // "corporate",
    // "synthwave",
    // "retro",
    // "cyberpunk",
    // "valentine",
    // "halloween",
    // "garden",
    // "forest",
    // "aqua",
    // "lofi",
    // "pastel",
    // "fantasy",
    // "wireframe",
    // "black",
    // "luxury",
    // "dracula",
    // "cmyk",
    // "autumn",
    // "business",
    // "acid",
    // "lemonade",
    // "night",
    // "coffee",
    // "winter",
    // "dim",
    // "nord",
    // "sunset",
])